### ISSUE TITLE
[UX] If non-US address is entered/selected, Affirm does not redirect anywhere after failure

### ISSUE THREAD

**Issue by Alchez** [DigiThinkIT/erpnext_affirm#8]
**Expected behaviour:**
Affirm fails gracefully, and redirects to a page where the customer is told that their payment was unsuccessful.

**Actual behaviour:**
After Affirm throws an error for a non-US address, and the customer selects the "Return to Merchant" button, the page gets stuck on "Please wait while we redirect you to Affirm...".

**Comment by vjFaLk** [comment]
This shouldn't happen at all, as in, the user shouldn't be able to select a non-US addres
